<?xml version="1.0"?>
<!DOCTYPE schedule [
  <!ELEMENT schedule (group-list, discipline-list, teacher-list)>
  <!ELEMENT group-list (group+)>
  <!ELEMENT group (day+)>
  <!ELEMENT day (couple+)>
  <!ELEMENT couple (time, couple-types)>
  <!ELEMENT time (#PCDATA)>
  <!ELEMENT couple-types (type+)>
  <!ELEMENT type (classroom, discipline-id, teachers)>
  <!ELEMENT classroom (#PCDATA)>
  <!ELEMENT discipline-id (#PCDATA)>
  <!ELEMENT teachers (teacher-id+)>
  <!ELEMENT teacher-id (#PCDATA)>
  <!ELEMENT discipline-list (discipline+)>
  <!ELEMENT discipline (title)>
  <!ELEMENT title (#PCDATA)>
  <!ELEMENT teacher-list (teacher+)>
  <!ELEMENT teacher (full-name, category)>
  <!ELEMENT full-name (#PCDATA)>
  <!ELEMENT category (#PCDATA)>
  <!ATTLIST group id ID #REQUIRED>
  <!ATTLIST day type CDATA #REQUIRED>
  <!ATTLIST discipline id ID #REQUIRED>
  <!ATTLIST teacher id ID #REQUIRED>
]>
<schedule>
    <group-list>
        <group id="530ст">
            <day type="Понеділок">
                <couple>
                    <time>08:00-09:35</time>
                    <couple-types>
                        <type>
                            <classroom>101 р.</classroom>
                            <discipline-id>D1</discipline-id>
                            <teachers>
                                <teacher-id>T1</teacher-id>
                            </teachers>
                        </type>
                    </couple-types>
                </couple>
                <couple>
                    <time>09:50-11:25</time>
                    <couple-types>
                        <type>
                            <classroom>101 р.</classroom>
                            <discipline-id>D2</discipline-id>
                            <teachers>
                                <teacher-id>T2</teacher-id>
                            </teachers>
                        </type>
                    </couple-types>
                </couple>
                <couple>
                    <time>11:55-13:30</time>
                    <couple-types>
                        <type>
                            <classroom>501 р.</classroom>
                            <discipline-id>D1</discipline-id>
                            <teachers>
                                <teacher-id>T1</teacher-id>
                            </teachers>
                        </type>
                        <type>
                            <classroom></classroom>
                            <discipline-id></discipline-id>
                            <teachers>
                                <teacher-id></teacher-id>
                            </teachers>
                        </type>
                    </couple-types>
                </couple>
                <couple>
                    <time>13:45-15:20</time>
                    <couple-types>
                        <type>
                            <classroom>501 р.</classroom>
                            <discipline-id>D1</discipline-id>
                            <teachers>
                                <teacher-id>T1</teacher-id>
                            </teachers>
                        </type>
                        <type>
                            <classroom></classroom>
                            <discipline-id></discipline-id>
                            <teachers>
                                <teacher-id></teacher-id>
                            </teachers>
                        </type>
                    </couple-types>
                </couple>
            </day>
            <day type="Вівторок">
                <couple>
                    <time>08:00-09:35</time>
                    <couple-types>
                        <type>
                            <classroom>101 р.</classroom>
                            <discipline-id>D2</discipline-id>
                            <teachers>
                                <teacher-id>T2</teacher-id>
                            </teachers>
                        </type>
                        <type>
                            <classroom>240 р.</classroom>
                            <discipline-id>D1</discipline-id>
                            <teachers>
                                <teacher-id>T1</teacher-id>
                            </teachers>
                        </type>
                    </couple-types>
                </couple>
                <couple>
                    <time>09:50-11:25</time>
                    <couple-types>
                        <type>
                            <classroom>223 р.</classroom>
                            <discipline-id>D3</discipline-id>
                            <teachers>
                                <teacher-id>T3</teacher-id>
                            </teachers>
                        </type>
                    </couple-types>
                </couple>
                <couple>
                    <time>11:55-13:30</time>
                    <couple-types>
                        <type>
                            <classroom>119 р.</classroom>
                            <discipline-id>D4</discipline-id>
                            <teachers>
                                <teacher-id>T4</teacher-id>
                            </teachers>
                        </type>
                    </couple-types>
                </couple>
                <couple>
                    <time>13:45-15:20</time>
                    <couple-types>
                        <type>
                            <classroom></classroom>
                            <discipline-id></discipline-id>
                            <teachers>
                                <teacher-id></teacher-id>
                            </teachers>
                        </type>
                        <type>
                            <classroom>223 р.</classroom>
                            <discipline-id>D3</discipline-id>
                            <teachers>
                                <teacher-id>T3</teacher-id>
                            </teachers>
                        </type>
                    </couple-types>
                </couple>
            </day>
            <day type="Середа">
                <couple>
                    <time>08:00-09:35</time>
                    <couple-types>
                        <type>
                            <classroom></classroom>
                            <discipline-id></discipline-id>
                            <teachers>
                                <teacher-id></teacher-id>
                            </teachers>
                        </type>
                    </couple-types>
                </couple>
                <couple>
                    <time>09:50-11:25</time>
                    <couple-types>
                        <type>
                            <classroom>106 лк.</classroom>
                            <discipline-id>D5</discipline-id>
                            <teachers>
                                <teacher-id>T5</teacher-id>
                            </teachers>
                        </type>
                    </couple-types>
                </couple>
                <couple>
                    <time>11:55-13:30</time>
                    <couple-types>
                        <type>
                            <classroom>217 р.</classroom>
                            <discipline-id>D3</discipline-id>
                            <teachers>
                                <teacher-id>T3</teacher-id>
                            </teachers>
                        </type>
                        <type>
                            <classroom>205 лк.</classroom>
                            <discipline-id>D5</discipline-id>
                            <teachers>
                                <teacher-id>T5</teacher-id>
                            </teachers>
                        </type>
                    </couple-types>
                </couple>
                <couple>
                    <time>13:45-15:20</time>
                    <couple-types>
                        <type>
                            <classroom>223 р.</classroom>
                            <discipline-id>D7</discipline-id>
                            <teachers>
                                <teacher-id>T3</teacher-id>
                                <teacher-id>T6</teacher-id>
                            </teachers>
                        </type>
                    </couple-types>
                </couple>
            </day>
            <day type="Четвер">
                <couple>
                    <time>08:00-09:35</time>
                    <couple-types>
                        <type>
                            <classroom></classroom>
                            <discipline-id></discipline-id>
                            <teachers>
                                <teacher-id></teacher-id>
                            </teachers>
                        </type>
                    </couple-types>
                </couple>
                <couple>
                    <time>09:50-11:25</time>
                    <couple-types>
                        <type>
                            <classroom></classroom>
                            <discipline-id></discipline-id>
                            <teachers>
                                <teacher-id></teacher-id>
                            </teachers>
                        </type>
                    </couple-types>
                </couple>
                <couple>
                    <time>11:55-13:30</time>
                    <couple-types>
                        <type>
                            <classroom></classroom>
                            <discipline-id></discipline-id>
                            <teachers>
                                <teacher-id></teacher-id>
                            </teachers>
                        </type>
                    </couple-types>
                </couple>
                <couple>
                    <time>13:45-15:20</time>
                    <couple-types>
                        <type>
                            <classroom></classroom>
                            <discipline-id></discipline-id>
                            <teachers>
                                <teacher-id></teacher-id>
                            </teachers>
                        </type>
                    </couple-types>
                </couple>
            </day>
            <day type="П'ятниця">
                <couple>
                    <time>08:00-09:35</time>
                    <couple-types>
                        <type>
                            <classroom>502 p.</classroom>
                            <discipline-id>D8</discipline-id>
                            <teachers>
                                <teacher-id>T2</teacher-id>
                                <teacher-id>T7</teacher-id>
                            </teachers>
                        </type>
                        <type>
                            <classroom></classroom>
                            <discipline-id></discipline-id>
                            <teachers>
                                <teacher-id></teacher-id>
                            </teachers>
                        </type>
                    </couple-types>
                </couple>
                <couple>
                    <time>09:50-11:25</time>
                    <couple-types>
                        <type>
                            <classroom>502 p.</classroom>
                            <discipline-id>D8</discipline-id>
                            <teachers>
                                <teacher-id>T2</teacher-id>
                                <teacher-id>T7</teacher-id>
                            </teachers>
                        </type>
                        <type>
                            <classroom></classroom>
                            <discipline-id></discipline-id>
                            <teachers>
                                <teacher-id></teacher-id>
                            </teachers>
                        </type>
                    </couple-types>
                </couple>
                <couple>
                    <time>11:55-13:30</time>
                    <couple-types>
                        <type>
                            <classroom>303 p.</classroom>
                            <discipline-id>D4</discipline-id>
                            <teachers>
                                <teacher-id>T4</teacher-id>
                            </teachers>
                        </type>
                        <type>
                            <classroom></classroom>
                            <discipline-id></discipline-id>
                            <teachers>
                                <teacher-id></teacher-id>
                            </teachers>
                        </type>
                    </couple-types>
                </couple>
                <couple>
                    <time>13:45-15:20</time>
                    <couple-types>
                        <type>
                            <classroom></classroom>
                            <discipline-id>D6</discipline-id>
                            <teachers>
                                <teacher-id></teacher-id>
                            </teachers>
                        </type>
                    </couple-types>
                </couple>
            </day>
        </group>
        <group id="535ст1">
            <day type="Понеділок">
                <couple>
                    <time>08:00-09:35</time>
                    <couple-types>
                        <type>
                            <classroom>238 р.</classroom>
                            <discipline-id>D9</discipline-id>
                            <teachers>
                                <teacher-id>T8</teacher-id>
                            </teachers>
                        </type>
                    </couple-types>
                </couple>
                <couple>
                    <time>09:50-11:25</time>
                    <couple-types>
                        <type>
                            <classroom>235 р.</classroom>
                            <discipline-id>D10</discipline-id>
                            <teachers>
                                <teacher-id>T9</teacher-id>
                            </teachers>
                        </type>
                    </couple-types>
                </couple>
                <couple>
                    <time>11:55-13:30</time>
                    <couple-types>
                        <type>
                            <classroom>123 р.</classroom>
                            <discipline-id>D10</discipline-id>
                            <teachers>
                                <teacher-id>T9</teacher-id>
                            </teachers>
                        </type>
                        <type>
                            <classroom></classroom>
                            <discipline-id></discipline-id>
                            <teachers>
                                <teacher-id></teacher-id>
                            </teachers>
                        </type>
                    </couple-types>
                </couple>
                <couple>
                    <time>13:45-15:20</time>
                    <couple-types>
                        <type>
                            <classroom>123 р.</classroom>
                            <discipline-id>D10</discipline-id>
                            <teachers>
                                <teacher-id>T9</teacher-id>
                            </teachers>
                        </type>
                        <type>
                            <classroom></classroom>
                            <discipline-id></discipline-id>
                            <teachers>
                                <teacher-id></teacher-id>
                            </teachers>
                        </type>
                    </couple-types>
                </couple>
            </day>
            <day type="Вівторок">
                <couple>
                    <time>08:00-09:35</time>
                    <couple-types>
                        <type>
                            <classroom></classroom>
                            <discipline-id></discipline-id>
                            <teachers>
                                <teacher-id></teacher-id>
                            </teachers>
                        </type>
                    </couple-types>
                </couple>
                <couple>
                    <time>09:50-11:25</time>
                    <couple-types>
                        <type>
                            <classroom>135 р.</classroom>
                            <discipline-id>D11</discipline-id>
                            <teachers>
                                <teacher-id>T10</teacher-id>
                            </teachers>
                        </type>
                        <type>
                            <classroom>135 р.</classroom>
                            <discipline-id>D12</discipline-id>
                            <teachers>
                                <teacher-id>T11</teacher-id>
                            </teachers>
                        </type>
                    </couple-types>
                </couple>
                <couple>
                    <time>11:55-13:30</time>
                    <couple-types>
                        <type>
                            <classroom>135 р.</classroom>
                            <discipline-id>D11</discipline-id>
                            <teachers>
                                <teacher-id>T10</teacher-id>
                            </teachers>
                        </type>
                    </couple-types>
                </couple>
                <couple>
                    <time>13:45-15:20</time>
                    <couple-types>
                        <type>
                            <classroom>238 р.</classroom>
                            <discipline-id>D9</discipline-id>
                            <teachers>
                                <teacher-id>T12</teacher-id>
                            </teachers>
                        </type>
                    </couple-types>
                </couple>
            </day>
            <day type="Середа">
                <couple>
                    <time>08:00-09:35</time>
                    <couple-types>
                        <type>
                            <classroom></classroom>
                            <discipline-id></discipline-id>
                            <teachers>
                                <teacher-id></teacher-id>
                            </teachers>
                        </type>
                    </couple-types>
                </couple>
                <couple>
                    <time>09:50-11:25</time>
                    <couple-types>
                        <type>
                            <classroom></classroom>
                            <discipline-id></discipline-id>
                            <teachers>
                                <teacher-id></teacher-id>
                            </teachers>
                        </type>
                    </couple-types>
                </couple>
                <couple>
                    <time>11:55-13:30</time>
                    <couple-types>
                        <type>
                            <classroom></classroom>
                            <discipline-id></discipline-id>
                            <teachers>
                                <teacher-id></teacher-id>
                            </teachers>
                        </type>
                        <type>
                            <classroom>205 лк.</classroom>
                            <discipline-id>D5</discipline-id>
                            <teachers>
                                <teacher-id>T5</teacher-id>
                            </teachers>
                        </type>
                    </couple-types>
                </couple>
                <couple>
                    <time>13:45-15:20</time>
                    <couple-types>
                        <type>
                            <classroom>414 лк.</classroom>
                            <discipline-id>D5</discipline-id>
                            <teachers>
                                <teacher-id>T5</teacher-id>
                            </teachers>
                        </type>
                    </couple-types>
                </couple>
            </day>
            <day type="Четвер">
                <couple>
                    <time>08:00-09:35</time>
                    <couple-types>
                        <type>
                            <classroom></classroom>
                            <discipline-id></discipline-id>
                            <teachers>
                                <teacher-id></teacher-id>
                            </teachers>
                        </type>
                    </couple-types>
                </couple>
                <couple>
                    <time>09:50-11:25</time>
                    <couple-types>
                        <type>
                            <classroom></classroom>
                            <discipline-id></discipline-id>
                            <teachers>
                                <teacher-id></teacher-id>
                            </teachers>
                        </type>
                    </couple-types>
                </couple>
                <couple>
                    <time>11:55-13:30</time>
                    <couple-types>
                        <type>
                            <classroom></classroom>
                            <discipline-id></discipline-id>
                            <teachers>
                                <teacher-id></teacher-id>
                            </teachers>
                        </type>
                        <type>
                            <classroom>136в р.</classroom>
                            <discipline-id>D14</discipline-id>
                            <teachers>
                                <teacher-id>T14</teacher-id>
                            </teachers>
                        </type>
                    </couple-types>
                </couple>
                <couple>
                    <time>13:45-15:20</time>
                    <couple-types>
                        <type>
                            <classroom></classroom>
                            <discipline-id></discipline-id>
                            <teachers>
                                <teacher-id></teacher-id>
                            </teachers>
                        </type>
                        <type>
                            <classroom>136в р.</classroom>
                            <discipline-id>D14</discipline-id>
                            <teachers>
                                <teacher-id>T14</teacher-id>
                            </teachers>
                        </type>
                    </couple-types>
                </couple>
            </day>
            <day type="П'ятниця">
                <couple>
                    <time>08:00-09:35</time>
                    <couple-types>
                        <type>
                            <classroom></classroom>
                            <discipline-id></discipline-id>
                            <teachers>
                                <teacher-id></teacher-id>
                            </teachers>
                        </type>
                    </couple-types>
                </couple>
                <couple>
                    <time>09:50-11:25</time>
                    <couple-types>
                        <type>
                            <classroom></classroom>
                            <discipline-id></discipline-id>
                            <teachers>
                                <teacher-id></teacher-id>
                            </teachers>
                        </type>
                    </couple-types>
                </couple>
                <couple>
                    <time>11:55-13:30</time>
                    <couple-types>
                        <type>
                            <classroom>123 р.</classroom>
                            <discipline-id>D14</discipline-id>
                            <teachers>
                                <teacher-id>T15</teacher-id>
                            </teachers>
                        </type>
                    </couple-types>
                </couple>
                <couple>
                    <time>13:45-15:20</time>
                    <couple-types>
                        <type>
                            <classroom></classroom>
                            <discipline-id>D6</discipline-id>
                            <teachers>
                                <teacher-id></teacher-id>
                            </teachers>
                        </type>
                    </couple-types>
                </couple>
            </day>
        </group>
        <group id="532ст">
            <day type="Понеділок">
                <couple>
                    <time>08:00-09:35</time>
                    <couple-types>
                        <type>
                            <classroom>101 р.</classroom>
                            <discipline-id>D1</discipline-id>
                            <teachers>
                                <teacher-id>T1</teacher-id>
                            </teachers>
                        </type>
                    </couple-types>
                </couple>
                <couple>
                    <time>09:50-11:25</time>
                    <couple-types>
                        <type>
                            <classroom>101 р.</classroom>
                            <discipline-id>D2</discipline-id>
                            <teachers>
                                <teacher-id>T2</teacher-id>
                            </teachers>
                        </type>
                    </couple-types>
                </couple>
                <couple>
                    <time>11:55-13:30</time>
                    <couple-types>
                        <type>
                            <classroom>501 р.</classroom>
                            <discipline-id>D1</discipline-id>
                            <teachers>
                                <teacher-id>T1</teacher-id>
                            </teachers>
                        </type>
                        <type>
                            <classroom></classroom>
                            <discipline-id></discipline-id>
                            <teachers>
                                <teacher-id></teacher-id>
                            </teachers>
                        </type>
                    </couple-types>
                </couple>
                <couple>
                    <time>13:45-15:20</time>
                    <couple-types>
                        <type>
                            <classroom>501 р.</classroom>
                            <discipline-id>D1</discipline-id>
                            <teachers>
                                <teacher-id>T1</teacher-id>
                            </teachers>
                        </type>
                        <type>
                            <classroom> </classroom>
                            <discipline-id> </discipline-id>
                            <teachers>
                                <teacher-id> </teacher-id>
                            </teachers>
                        </type>
                    </couple-types>
                </couple>
            </day>
            <day type="Вівторок">
                <couple>
                    <time>08:00-09:35</time>
                    <couple-types>
                        <type>
                            <classroom>101 р.</classroom>
                            <discipline-id>D2</discipline-id>
                            <teachers>
                                <teacher-id>T2</teacher-id>
                            </teachers>
                        </type>
                        <type>
                            <classroom>240 р.</classroom>
                            <discipline-id>D1</discipline-id>
                            <teachers>
                                <teacher-id>T1</teacher-id>
                            </teachers>
                        </type>
                    </couple-types>
                </couple>
                <couple>
                    <time>09:50-11:25</time>
                    <couple-types>
                        <type>
                            <classroom>102 р.</classroom>
                            <discipline-id>D15</discipline-id>
                            <teachers>
                                <teacher-id>T16</teacher-id>
                            </teachers>
                        </type>
                    </couple-types>
                </couple>
                <couple>
                    <time>11:55-13:30</time>
                    <couple-types>
                        <type>
                            <classroom>102 р.</classroom>
                            <discipline-id>D15</discipline-id>
                            <teachers>
                                <teacher-id>T16</teacher-id>
                            </teachers>
                        </type>